### ISSUE TITLE
Strict mode used globally

### ISSUE THREAD

**Issue by szuperaz** [meanie/angular-http-buffer#1]
Hi,

I noticed that you declare strict mode globally, which can cause errors when your library is concateneted and minified together with other libraries, which don't support strict mode.
If you could declare it inside the function, that would be much help.

Thanks,
Zita

**Comment by adambuczynski** [comment]
Hi @szuperaz, thanks for raising this. 

It seems that the babel `es2015` preset automatically adds this, even though my build process already applied this to all packages as function form.

I have converted all my packages to use https://github.com/fancyboynet/babel-preset-es2015-without-strict instead, so that should solve the issue. Fixed in 1.2.0.
